image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 15.4.0-debian-11-r56

auth:
  database: pms_db
  password: eluon123
  username: pms
  postgresPassword: eluon123
metrics:
  enabled: true
primary:
  resources:
    limits:
      memory: 2Gi
      cpu: 2
    requests:
      memory: 256Mi
      cpu: 250m
  persistence:
    storageClass: nfs-client
    size: 15Gi


# readReplicas:
#   resources:
#     limits:
#       memory: 2Gi
#       cpu: 2
#     requests:
#       memory: 256Mi
#       cpu: 250m

