---
# Source: postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: pms-postgresql
  namespace: "default"
  labels:
    app.kubernetes.io/instance: pms-postgresql
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 16.2.0
    helm.sh/chart: postgresql-15.0.0
type: Opaque
data:
  postgres-password: "ZWx1b24xMjM="
  password: "ZWx1b24xMjM="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
